apiVersion: v1
kind: Service
metadata:
  name: microservicio-datum-3
  labels:
    app: microservicio-datum-3  
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: microservicio-datum-3
