apiVersion: v1
kind: Service
metadata:
  name: microservicio-datum-1
  labels:
    app: microservicio-datum-1    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: microservicio-datum-1
